 lerobot-train \
  --dataset.repo_id=eunjuri/soft_manip_data \
  --output_dir=./outputs/xvla_training \
  --job_name=xvla_training \
  --policy.path="lerobot/xvla-base" \
  --policy.repo_id="eunjuri/xvla-your-robot" \
  --policy.dtype=bfloat16 \
  --policy.action_mode=auto \
  --steps=20000 \
  --policy.device=cuda \
  --policy.freeze_vision_encoder=false \
  --policy.freeze_language_encoder=false \
  --policy.train_policy_transformer=true \
  --policy.train_soft_prompts=true \
  --wandb.enable=true \
  --wandb.project baselines \
  --rename_map='{"observation.images.cam_left_high": "observation.images.camera1"}'